In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3])
print(a)



[1 2 3]


In [5]:
import numpy as np
list=[10,20,30]
a=np.array(list)
print(a)
print(np.ndim(a))

[10 20 30]
1


In [8]:
import numpy as np
list=[10,20,30],[12,23,44]
a=np.array(list)
print(a)
print(np.ndim(a))

[[10 20 30]
 [12 23 44]]
2


In [12]:
import numpy as np
a=[[[5,6,7],[8,67,55],[12,33,45],[23,43,21]]]
a=np.array(a)
print(a)
print(np.ndim(a))

[[[ 5  6  7]
  [ 8 67 55]
  [12 33 45]
  [23 43 21]]]
3


In [13]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [14]:
import numpy as np
arr=np.array([2,4,56,])
print(arr[2])

56


In [17]:
import numpy as np
arr=np.array([[1,2,3,4],[6,7,8,9]])
print('2nd element on 1st row:',arr[0,1])

2nd element on 1st row: 2


In [20]:
import numpy as np
arr=np.array([[[1,2,3,4,],[23,45,65,22],[12,23,31]]])
print('3rd element on 2nd row:',arr[0,2])

3rd element on 2nd row: [12, 23, 31]


In [21]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,1,2])
                                      
                                      
                                      
                                      
                                      
                                    

6


In [30]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,0,2])
print(arr[0,1,2])
print(arr[0,2,2])
print(arr[0,3,2])
res=arr[0,0,2]+arr[0,1,2]+arr[0,2,2]+arr[0,3,2]
print(res)




3
6
9
12
30
